#----------------------------------------------------------------------------
# https://home-assistant.io/components/logger/
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
#----------------------------------------------------------------------------

  default: warn
  logs:
#    # Added to remove some log records at startup
#    homeassistant.components.media_player.squeezebox: fatal
#    homeassistant.components.sensor.mold_indicator: fatal
#    homeassistant.components.sensor: error
#    netdisco.ssdp: error


    # Added to remove:
    # 2019-12-30 22:39:45 ERROR (MainThread) [homeassistant.components.squeezebox.media_player] Failed communicating with LMS: <class 'aiohttp.client_exceptions.ClientConnectorError'>
    homeassistant.components.squeezebox.media_player: fatal

    # 2019-12-30 22:39:45 WARNING (MainThread) [homeassistant.components.media_player] Platform squeezebox not ready yet. Retrying in 120 seconds.
    # 2019-12-30 22:40:20 WARNING (MainThread) [homeassistant.components.media_player] Updating yamaha media_player took longer than the scheduled update interval 0:00:10
    homeassistant.components.media_player: error

    # 2019-12-30 22:40:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.yamaha_receiver_zone_2 is taking over 10 seconds
    homeassistant.helpers.entity: error

    # 2019-12-30 22:56:49 WARNING (SyncWorker_8) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: empty response
    homeassistant.components.waze_travel_time.sensor: error

    aioharmony.hubconnector: fatal
    # 2019-12-31 07:17:22 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Exception on post: Connection timeout to host http://192.168.1.247:8088/
    # 2019-12-31 07:17:22 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Unable to retrieve HUB id
    # 2019-12-31 07:22:31 ERROR (MainThread) [aioharmony.hubconnector] 192.168.1.247: Connection timed out for hub 12135421

    # Added to remove:
    # 2020-08-23 11:42:34 WARNING (MainThread) [homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_info] Camera 1 Image when person detected and camera mode Info: Already running
#    homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_day: error
#    homeassistant.components.automation.camera_2_image_when_person_detected_and_camera_mode_day: error
#    homeassistant.components.automation.camera_1_image_when_person_detected_and_camera_mode_away: error
#    homeassistant.components.automation.camera_2_image_when_person_detected_and_camera_mode_away: error

    # 2020-08-26 05:20:39 WARNING (MainThread) [homeassistant.components.automation.camera_1_image_processing_mode_warning] Camera 1 Image processing mode Warning: Already running
#    homeassistant.components.automation.camera_1_image_processing_mode_away: error
#    homeassistant.components.automation.camera_2_image_processing_mode_away: error


    # 2020-10-07 20:21:33 WARNING (MainThread) [homeassistant.components.automation.camera_1_folder_watcher_activated] Camera 1 Folder Watcher activated: Already running
    homeassistant.components.automation.camera_1_folder_watcher_activated: warning
    homeassistant.components.automation.camera_2_folder_watcher_activated: warning